"""Modèle UtilisateurClient

Revision ID: 07192b20c2ea
Revises: 795341d1b585
Create Date: 2025-07-29 20:44:41.597170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07192b20c2ea'
down_revision = '795341d1b585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur_client',
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_liaison', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utilisateur_id', 'client_id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_utilisateur_id_fkey', type_='foreignkey')
        batch_op.drop_column('utilisateur_id')

    with op.batch_alter_table('parametres_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_2fa', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametres_compte', schema=None) as batch_op:
        batch_op.drop_column('secret_2fa')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('client_utilisateur_id_fkey', 'utilisateur', ['utilisateur_id'], ['id'])

    op.drop_table('utilisateur_client')
    # ### end Alembic commands ###
