"""Suppression des colonnes 2FA dans ParametresCompte

Revision ID: 50625f812388
Revises: 07192b20c2ea
Create Date: 2025-07-29 21:02:18.640256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50625f812388'
down_revision = '07192b20c2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametres_compte', schema=None) as batch_op:
        batch_op.drop_column('uses_2fa')
        batch_op.drop_column('secret_2fa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametres_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_2fa', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uses_2fa', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
