"""Ajout des modèles Devis, Paiement, etc.

Revision ID: 6187c5036442
Revises: 0d67e63b7d88
Create Date: 2025-04-14 15:28:24.147731

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6187c5036442"
down_revision = "0d67e63b7d88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("date_inscription", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "blog_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titre", sa.String(length=200), nullable=False),
        sa.Column("contenu", sa.Text(), nullable=False),
        sa.Column("date_publication", sa.DateTime(), nullable=True),
        sa.Column("auteur_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auteur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "devis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=False),
        sa.Column("secteur", sa.String(length=100), nullable=True),
        sa.Column("nom", sa.String(length=100), nullable=True),
        sa.Column("type_service", sa.String(length=100), nullable=True),
        sa.Column("date_rdv", sa.String(length=50), nullable=True),
        sa.Column("heure_rdv", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "historique",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=True),
        sa.Column("date_visite", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paiement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=False),
        sa.Column("montant", sa.Float(), nullable=True),
        sa.Column("date_transaction", sa.DateTime(), nullable=True),
        sa.Column("statut", sa.String(length=50), nullable=True),
        sa.Column("mode_paiement", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=False),
        sa.Column("langue", sa.String(length=10), nullable=True),
        sa.Column("theme", sa.String(length=10), nullable=True),
        sa.Column("notif_email", sa.Boolean(), nullable=True),
        sa.Column("notif_sms", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "support_ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("utilisateur_id", sa.Integer(), nullable=True),
        sa.Column("sujet", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("date_creation", sa.DateTime(), nullable=True),
        sa.Column("statut", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["utilisateur_id"],
            ["utilisateur.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_ticket")
    op.drop_table("preferences")
    op.drop_table("paiement")
    op.drop_table("historique")
    op.drop_table("devis")
    op.drop_table("blog_post")
    op.drop_table("newsletter")
    # ### end Alembic commands ###
