"""Ajout de la colonne email_chiffre dans Client

Revision ID: 795341d1b585
Revises: 6187c5036442
Create Date: 2025-07-01 17:45:33.859834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '795341d1b585'
down_revision = '6187c5036442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres_compte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('langue', sa.String(length=10), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('notif_email', sa.Boolean(), nullable=True),
    sa.Column('notif_sms', sa.Boolean(), nullable=True),
    sa.Column('uses_2fa', sa.Boolean(), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('nom_facturation', sa.String(length=255), nullable=True),
    sa.Column('adresse_facturation', sa.String(length=255), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_chiffre', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('client_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email_chiffre'])
        batch_op.drop_column('email')

    with op.batch_alter_table('historique', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=255), nullable=False))
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('path')
        batch_op.drop_column('date_visite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historique', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_visite', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('action')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('client_email_key', ['email'])
        batch_op.drop_column('email_chiffre')

    op.drop_table('parametres_compte')
    # ### end Alembic commands ###
