"""Modèle ParametresCompte

Revision ID: d38d41a05fc4
Revises: f6ef0d5cc4e8
Create Date: 2025-08-18 13:04:15.365195

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d38d41a05fc4"
down_revision = "f6ef0d5cc4e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column(
            "utilisateur_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column(
            "utilisateur_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
